export const GIFTS_DATA = [
  { id: 1, cat: "Acrylic",    comingSoon: false, tag: "Signature", detailPage: "/gifts/acrylic-photo",
    folder: "/images/gifts/acrylic-photo", name: "Acrylic Engraved Photo",
    desc: "Preserve your cherished memories forever with a beautifully detailed, crystal-clear acrylic laser engraving.",
    material: "Premium clear acrylic", price: "LKR 900 – 1,500",
    img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=680&fit=crop&auto=format" },
  { id: 2, cat: "Notebooks",  comingSoon: true, tag: "Coming Soon",
    folder: "/images/gifts/notebooks", name: "Engraved Notebooks",
    desc: "Elevate your daily writing with a personalized notebook featuring a custom-etched, sophisticated design.",
    material: "Kraft & leather cover", price: "–",
    img: "https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?w=600&h=680&fit=crop&auto=format" },
  { id: 3, cat: "Art & Photo", comingSoon: true,  tag: "Coming Soon",
    folder: "/images/gifts/leaf-art", name: "Leaf Art",
    desc: "Experience the delicate beauty of nature combined with precision laser craftsmanship on an authentic, intricately carved leaf.",
    material: "Natural leaf · Backlit", price: "–",
    img: "https://images.unsplash.com/photo-1699508059832-3488136a6e84?w=600&h=680&fit=crop&auto=format" },
  { id: 4, cat: "Wood",       comingSoon: true, tag: "Coming Soon",
    folder: "/images/gifts/wood-coaster", name: "Wood Engraved Coaster",
    desc: "Protect your surfaces while adding a rustic, elegant touch to your coffee table with custom-etched wooden coasters.",
    material: "Birchwood · MDF", price: "–",
    img: "https://images.unsplash.com/photo-1632424014490-766d1664a5a3?w=600&h=680&fit=crop&auto=format" },
  { id: 5, cat: "Key Tags",   comingSoon: false, tag: null, detailPage: "/gifts/acrylic-keytag",
    folder: "/images/gifts/acrylic-keytag", name: "Acrylic Key Tags",
    desc: "Carry a piece of personalized style wherever you go with durable, sleek, and finely engraved acrylic keychains.",
    material: "Clear & coloured acrylic · 55×35 mm", price: "LKR 100 – 150",
    img: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=680&fit=crop&auto=format" },
  { id: 6, cat: "Key Tags",   comingSoon: false, tag: null, detailPage: "/gifts/wooden-keytag",
    folder: "/images/gifts/wooden-keytag", name: "Wooden Key Tags",
    desc: "Add a warm, natural aesthetic to your daily essentials with custom-crafted, durable wooden key tags.",
    material: "Birchwood · MDF · 55×35 mm", price: "LKR 100 – 150",
    img: "https://images.unsplash.com/photo-1736967225486-d3c9298b8a5e?w=600&h=680&fit=crop&auto=format" },
  { id: 7, cat: "Acrylic",    comingSoon: true, tag: "Coming Soon",
    folder: "/images/gifts/ultrasonic-brackets", name: "Ultrasonic Brackets",
    desc: "A precision-engineered, laser-cut mounting bracket designed to securely hold ultrasonic sensors for your technical builds.",
    material: "Acrylic · MDF", price: "–",
    img: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&h=680&fit=crop&auto=format" },
  { id: 8, cat: "Art & Photo", comingSoon: true, tag: "Coming Soon",
    folder: "/images/gifts/tile-photo", name: "Tile Engraved Photo",
    desc: "Transform a classic ceramic tile into a stunning, high-contrast permanent portrait that lasts a lifetime.",
    material: "Ceramic tile", price: "–",
    img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=680&fit=crop&auto=format" },
];

export const GIFT_CATS = ["All", "Acrylic", "Wood", "Key Tags", "Notebooks", "Art & Photo"] as const;


